name: Generate release-artifacts

on:
  release:
    types:
      - created

jobs:
  build:
    name: Publish release for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: join-layers
            asset_name: join-layers-linux-amd64
          - os: windows-latest
            artifact_name: join-layers.exe
            asset_name: join-layers-windows-amd64.exe
          - os: macos-latest
            artifact_name: join-layers
            asset_name: join-layers-macos-amd64

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.18'

      - name: Build on Windows
        if: matrix.os == 'windows-latest'
        run: go build -o ${{ matrix.artifact_name }} .

      - name: Build on macOS
        if: matrix.os == 'macos-latest'
        run: go build -o ${{ matrix.artifact_name }} .

      - name: Build on Windows
        if: matrix.os == 'ubuntu-latest'
        run: go build -o ${{ matrix.artifact_name }} .

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
